export enum AppText{
    appName = 'CIVION',
    Hey = "Hey",
    LoginNow = "Login Now!", 
    ForgotPassword = "Forgot Password?",
    OR = "OR",
    DontHaveAccount ="Don't have an account?",
    SignUp = "Sign Up",
    Poweredby = "Powered by",
    KusiarProjectServicesInc = "Kusiar Project Services Inc.",

    ChangePassword = "Change Password",
    CurrentPassword = "Current Password",
    NewPassword = "New Password",
    ConfirmPassword = "Confirm Password",

    ProjectList = "Project List",
    ComingSoon = "Coming Soon..",
    AddDailyEntry = "Add a Daily Entry",
    AddWeeklyEntry = "Add a Weekly Entry",
    AddDailyDiary = "Add a Daily Diary",

    WeeklyEntry = "Weekly Entry",
    DailyDairyEntry = "Daily Diary Entry",
    DailyEntry = "Daily Entry",

    EnterDescriptiondetails = 'Enter Details',
    EnterEquipmentDetails = 'Equipment Details',
    EnterLabourDetails = 'Labour Details',
    EnterVisitorDetails = 'Visitor Details',
    FillDeclerationForm = "Fill Decleration Form",
    JobHazardAnalysis ="Job Hazard Analysis",
    
    EnterProjectDetails = 'Project Details',
    HazardSelection = "Hazard Selection",
    TaskAddition = "Task Addition",
    GeneralDetails = "General Details",
    PreviousEntryMessage = "We found previous form data. Would you like to use it?",
    Mileage = "Mileage",
    MileageTracker = "Mileage Tracker",
    StartRide = "Swipe to Start Ride",
    EndRide = "Swipe to End Ride",
    RideCompleted = "Ride Completed",
    Expense = "Expense",
    CreateNewExpense = "Create New Expense",
    ExpensePreview = "Expense Preview",
    ExpenseDetails = "Expense Details",
    HighTemp = "HighTemp",
    LowTemp = "LowTemp",
    Pending = "Pending",
    Approved = "Approved",
    Rejected = "Rejected",
    Notification = "Notification",
    Done= "Done",
    ImageSelection="Photo files Selection",

    EnterInvoiceDetails = 'Enter Invoice Details',
    InspectorNameTheirDetails = 'Inspector Name & Their Details',
    Invoice = 'Invoice',
   

}

