export enum ScreenType {
    PHOTO_FILE = "PHOTO_FILE",
    DAILY_ENTRY = "DAILY_ENTRY",
    WEEKLY_ENTRY = "WEEKLY_ENTRY",
    DAILY_DAIRY_ENTRY = "DAILY_DAIRY_ENTRY",
    INVOICE = "INVOICE",
    PDF = "PDF"
    
}