
export enum screenNames {
    LoginScreen = 'LoginScreen',
    RegisterScreen = 'RegisterScreen',
    SplashScreen = 'SplashScreen',
    ForgotPasswordScreen = 'ForgotPasswordScreen',
    HomeScreen = 'HomeScreen',
    HomeTabs = 'HomeTabs',
    MainApp = 'MainApp' ,
    ReportScreen = "ReportScreen",
    MileageScreen = "MileageScreen",
    ExpenseScreen = "ExpenseScreen",
    InvoiceScreen = "InvoiceScreen",
    VerifyOTPScreen = "VerifyOTPScreen",
    WebViewScreen = "WebViewScreen",
    AddUserScreen = "AddUserScreen",
    LogoScreen = "LogoScreen",
    LogoUploadScreen = "LogoUploadScreen",
    ScheduleScreen = "ScheduleScreen",
    CreateScheduleScreen = "CreateScheduleScreen",
    ResetPasswordScreen = "ResetPasswordScreen",
    ScheduleListScreen = "ScheduleListScreen",
    PhotoFilesScreen = "PhotoFilesScreen",
    DailyEntryScreen = "DailyEntryScreen",
    WeeklyEntryScreen = "WeeklyEntryScreen",
    DailyDairyEntryScreen = "DailyDairyEntryScreen",
    JobHazardScreen = "JobHazardScreen",
    CreateJobHazard = "CreateJobHazard",
    ImageViewer = "ImageViewer",
    ViewAllPhotos = "ViewAllPhotos",
    PreviewJobHazard = "PreviewJobHazard",
    CreateMileageScreen = "CreateMileageScreen",
    CreateExpenseScreen = "CreateExpenseScreen",
    PreviewExpenseScreen = "PreviewExpenseScreen",
    ExpenseDetailScreen = "ExpenseDetailScreen",
    DailyPreviewScreen = "DailyPreviewScreen",
    WeeklyPreviewScreen = "WeeklyPreviewScreen",
    DailyDairyPreviewScreen = "DailyDairyPreviewScreen",
    NotificationScreen = "NotificationScreen",
    ImageSelectionScreen = "ImageSelectionScreen",
    WeeklyDetailScreen = "WeeklyDetailScreen",
    CreateInvoiceScreen="CreateInvoiceScreen",
    InvoicePreviewScreen="InvoicePreviewScreen",
    WorkFromEntryScreen="WorkFromEntryScreen",
    ReportPdfScreen="ReportPdfScreen"

    
}